### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by Tusker13-04** [GDGVIT/vitty#22]
The app and widget were not working properly .. soi decided to uninstall and reinstall the app .
I tried uploading my timetable to the website ,  but it is stuck in loading screen after submitting the pasted timetable.
![image](https://github.com/GDGVIT/vitty/assets/63436014/ffc686b6-a54d-4647-8785-aea7c70d1bab)

I request you to look into this issue at the earliest .
Technical Details :
Browser used: Latest version of Chrome
Extensions added :ViBoot

**Comment by BearTS** [comment]
Ah yep, looking towards it right now!

**Comment by Dhruv9449** [comment]
Fixed! Should work now.

**Comment by Tusker13-04** [comment]
Thankyou for the immediate response and quick fix 👍
